### ISSUE TITLE
packages.el is probably not a good idea

### ISSUE THREAD

**Issue by tarsius** [roman/clocker.el#1]
I am not sure what that file is for but am pretty sure it's not a good idea to have a library named `packages.el` checked in. It's not all that unlikely that someone is going to write a package by that name, probably some extension to `package.el`.

**Comment by roman** [comment]
I did add the file as a way to integrate out of the box with spacemacs... not sure what other approaches can I use in order to accomplish that. 

Let me talk with the people from spacemacs to get a shed of light on how to do that.

Thanks for your feedback.
