### ISSUE TITLE
defconst: Symbol's function definition is void: powerline-raw

### ISSUE THREAD

**Issue by idontgetoutmuch** [roman/clocker.el#2]
I installed the package but it didn't seem to open any .org file or give me a message that it couldn't find one. Instead I got the message in the title of this issue.

**Comment by roman** [comment]
I think it is because I'm using powerline-raw on the defconst clocker-mode-line-widget without ensuring that it is defined. I'll add a fix to that, thanks

**Comment by roman** [comment]
I uploaded a new version (v0.0.6) can you try out now? Thanks.

**Comment by idontgetoutmuch** [comment]
That's fixed it thanks.
