### ISSUE TITLE
Only open *files* ending with .org

### ISSUE THREAD

**Issue by kasimon** [roman/clocker.el#3]
In my homedirectory, I have no .org file but a directory ~/.conkeror.mozdev.org/. When I try to save a file with no org file in its directory tree, clocker openes ~/.conkeror.mozdev.org/ in dired. I doubt this is the intendet behaviour ;)

**Comment by roman** [comment]
Not at all...

I've been having this issue as well, but didn't realize it was because of that being a folder, going to fix it soonish as this is something that really annoys me

**Comment by roman** [comment]
Fixed on v0.0.7

**Comment by roman** [comment]
UPDATE: try v0.0.9 better
