### ISSUE TITLE
Feature Request: Add ignore options to nagging dialog

### ISSUE THREAD

**Issue by kasimon** [roman/clocker.el#4]
It would be great if clocker's 'nagging' dialog would offer to add either the file, directory or the current major mode to it's ignore list interactively.

**Comment by roman** [comment]
Can you expand a bit on this?

Like, being able to say where to nag or not to nag? A custom variable that has a list of these perhaps?

**Comment by roman** [comment]
Oh I forgot we added this vars already, do you want the prompt to ask if you want to nag you for that particular file?

**Comment by kasimon** [comment]
Yes, I want to be able to have the current file or mode ignored, somehow
like the i key in magit-status.

**Comment by roman** [comment]
I'm not 100% sure if I want this feature, if it is really easy to add stuff to ignore list, then at some point it would defeat the purpose. Adding it only on a mode basis makes more sense, either I want clocker to be involved on this mode or not at all, doing it on a file basis seems like cheating ourselves a bit. Probably going to add a `clocker-ignore-current-mode` with a confirmation question, add it to the list of clocker-skip-after-save variable.

**Comment by kasimon** [comment]
Sounds good to me. The most annoying case for me is currently when
composing a mail in mu4e clocker interferes with the mail sending process,
there an easy way to add mode based exceptions would really help.

**Comment by roman** [comment]
I added two new functions on v0.0.8
- `clocker-skip-on-major-mode`
- `clocker-stop-skip-on-major-mode`

This will allow you to dynamically add or remove valid modes from the `clocker-skip-after-save-hook-on-mode` custom variable.

Please use this two functions to modify your variable accordingly.
